name: "CI"

on: [push]

jobs:
    type-check:
      name: type-check
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm install
              npm run type-check
    lint:
      name: lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm install
              npm run lint
    test:
      name: test
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm install
              npm run test

    test_regression:
      name: test:regression
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm install
              npm run test:regression